sudo: required
dist: trusty

language: c

env:
  matrix:
    - CROSS=y

script:
  - cd src
  - make -f win/Makefile.mingw

addons:
  apt:
    packages:
      - binutils-mingw-w64-i686
      - gcc-mingw-w64-i686
      - binutils-mingw-w64-x86-64
      - gcc-mingw-w64-x86-64
      - gcc-mingw-w64
      - mingw-w64
